### ISSUE TITLE
How to solve the error train_dreambooth_lora.py FAILED?

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [HansenHuang0823/PlacidDreamer#5]
Sorry to interupt you, but I have found that after I ran the command `sh train_dreambooth_lora.sh`, it shows that 
`Traceback (most recent call last):
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1088, in launch_command
    multi_gpu_launcher(args)
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 733, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
train_dreambooth_lora.py FAILED
Failures:
  <NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
  time      : 2024-07-29_13:25:08
  host      : mercury
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2647668)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html`

How can I solve the problem?

**Comment by HansenHuang0823** [comment]
It's very hard to solve a distributed pytorch problem online, so I suggest you run it on single GPU.

**Comment by HansenHuang0823** [comment]
<img width="863" alt="accelerate_config" src="https://github.com/user-attachments/assets/186443fd-efae-44ae-af93-bce6494b1c49">
Then you can run train_dreambooth_lora.sh on single GPU.

**Comment by ZhenyuSun-Walker** [comment]
I've emploied your suggestions on accelerate config. However, it shows error information below
![image](https://github.com/user-attachments/assets/9fc0b56b-41fa-4a00-8ec7-26da856675cb)

**Comment by HansenHuang0823** [comment]
```
pip install peft
```
will solve this problem.

**Comment by ZhenyuSun-Walker** [comment]
The configuration is already satisfied. The error above seems not to be caused by that.

**Comment by HansenHuang0823** [comment]
Then it may be caused by the confliction between peft and transformers versions.
```
pip install -U peft transformers diffusers
```

**Comment by ZhenyuSun-Walker** [comment]
Great！This is exactly where the crux of the problem lies.
However, a new problem has arisen when I run the command `python train.py --opt configs/cactus.yaml --lambda_ 18.0 --name cactus --lora_path lora_checkpoints/cactus `
The details are shown as below.
![image](https://github.com/user-attachments/assets/b676926d-8cf6-4f34-9808-1530531a5416)

**Comment by HansenHuang0823** [comment]
```
pip uninstall diff_gaussian_rasterization
pip uninstall simple_knn
pip install -e submodules/diff-gaussian-rasterization/
pip install -e submodules/simple-knn/
```
If this cannot solve your problem,  please provide with your pytorch version ```pip list``` and cuda version ```nvcc -V```.

**Comment by ZhenyuSun-Walker** [comment]
Perhaps I need to execute `pip install --upgrade diff_gaussian_rasterization torch`?
The command is currently running, and I'll report the result ASAP. Thank you for your patience!

**Comment by ZhenyuSun-Walker** [comment]
OK, I'll try your sugestions!

**Comment by HansenHuang0823** [comment]
Yes, it appears that this issue is stemming from a compatibility conflict between the versions of PyTorch, CUDA, and the PyTorch version used during the compilation of the submodules.
